[package]
name = "onitama-alphazero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onitama_game = { path = "onitama-game" }

[workspace]
members = [
    "onitama-game", "gui", "onitama-gui"
]