[package]
name = "onitama-alphazero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onitama_game = { path = "../onitama-game" }
rand = "0.8.5"
tch = "0.11.0"